services:
  # 数据库服务
  db:
    image: postgres:16
    container_name: todo-db
    restart: always
    environment:
      POSTGRES_USER: zelin
      POSTGRES_PASSWORD: your_password
      POSTGRES_DB: todo_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data # 使用命名卷，方便管理

  # 后端应用服务
  app:
    image: ghcr.io/playeriv65/todo-backend:latest
    # build: .
    container_name: todo-app
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      # 通过环境变量覆盖 application.properties 里的配置
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/todo_db
      - SPRING_DATASOURCE_USERNAME=zelin
      - SPRING_DATASOURCE_PASSWORD=your_password
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

volumes:
  postgres_data: